# Generated by Django 6.0.5 on 2026-06-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('to_admins', models.BooleanField(default=True, verbose_name='Show to Admins')),
                ('to_teachers', models.BooleanField(default=True, verbose_name='Show to Teachers')),
                ('to_students', models.BooleanField(default=True, verbose_name='Show to Students')),
                ('to_parents', models.BooleanField(default=True, verbose_name='Show to Parents')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
