# Generated by Django 6.0.5 on 2026-08-13 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='SchoolMS', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/favicon/')),
                ('primary_color', models.CharField(default='#5a67d8', help_text='Hex color e.g. #5a67d8', max_length=7)),
                ('secondary_color', models.CharField(default='#4c51bf', max_length=7)),
                ('sidebar_color', models.CharField(default='#ffffff', max_length=7)),
                ('navbar_color', models.CharField(default='#1a202c', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('to_admins', models.BooleanField(default=True, verbose_name='Show to Admins')),
                ('to_teachers', models.BooleanField(default=True, verbose_name='Show to Teachers')),
                ('to_students', models.BooleanField(default=True, verbose_name='Show to Students')),
                ('to_parents', models.BooleanField(default=True, verbose_name='Show to Parents')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassNamingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade', models.PositiveSmallIntegerField()),
                ('to_grade', models.PositiveSmallIntegerField()),
                ('naming_convention', models.CharField(choices=[('grade', 'Grade'), ('standard', 'Standard'), ('form', 'Form'), ('custom', 'Custom')], default='grade', max_length=20)),
                ('custom_name', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('junior', 'Junior Secondary'), ('secondary', 'Senior Secondary')], max_length=20)),
                ('ranking_method', models.CharField(choices=[('marks', 'Total Marks'), ('points', 'Points')], default='marks', max_length=20)),
                ('school_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_naming_rules', to='dashboard.schoolsettings')),
            ],
            options={
                'ordering': ['from_grade'],
            },
        ),
    ]
