# Generated by Django 6.0.6 on 2026-07-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='SchoolMS', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/favicon/')),
                ('primary_color', models.CharField(default='#5a67d8', help_text='Hex color e.g. #5a67d8', max_length=7)),
                ('secondary_color', models.CharField(default='#4c51bf', max_length=7)),
                ('sidebar_color', models.CharField(default='#ffffff', max_length=7)),
                ('navbar_color', models.CharField(default='#1a202c', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
    ]
