# Generated by Django 6.0.5 on 2026-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0003_student_blood_group_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.studentclass'),
        ),
    ]
