# Generated by Django 6.0.6 on 2026-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_teacher_assigned_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
