# Generated by Django 6.0.6 on 2026-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_teacher_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grades_visible',
            field=models.BooleanField(default=False, help_text='Show grades to parent when fees are paid.'),
        ),
    ]
