# Generated by Django 6.0.5 on 2026-06-23 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('salaries', 'Salaries & Wages'), ('utilities', 'Utilities & Bills'), ('maintenance', 'Repairs & Maintenance'), ('supplies', 'Educational Supplies'), ('food', 'Cafeteria & Catering'), ('other', 'Other Expenses')], default='other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_spent', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_spent'],
            },
        ),
    ]
