# Generated by Django 6.0.5 on 2026-08-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20, unique=True)),
                ('grade_level', models.PositiveSmallIntegerField()),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['grade_level', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='StudentTermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_late', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('follows_directions', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('works_independently', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('attentive_in_class', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('does_work_neatly', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('completes_daily_work', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('completes_homework', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('is_courteous', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('gets_along_with_others', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('exhibits_self_control', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('does_not_disturb_others', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('shows_respect', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('responds_to_correction', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('teacher_comment', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('promotion_status', models.CharField(choices=[('promoted', 'Promoted'), ('probation', 'Promoted on Probation'), ('not', 'Not Promoted'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.PositiveIntegerField(default=0)),
                ('exam_score', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.academicsession')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
