# Generated by Django 6.0.5 on 2026-08-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='people.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.studentclass'),
        ),
        migrations.AddField(
            model_name='studenttermreport',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studenttermreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='people.student'),
        ),
        migrations.AddField(
            model_name='studenttermreport',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentclass'),
        ),
        migrations.AddField(
            model_name='studenttermreport',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttermreport',
            unique_together={('student', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'session', 'term')},
        ),
    ]
