# Generated by Django 6.0.6 on 2026-07-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0006_student_grades_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_late', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('follows_directions', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('works_independently', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('attentive_in_class', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('does_work_neatly', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('completes_daily_work', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('completes_homework', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('is_courteous', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('gets_along_with_others', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('exhibits_self_control', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('does_not_disturb_others', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('shows_respect', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('responds_to_correction', models.IntegerField(choices=[(1, '1 - Excellent'), (2, '2 - Good'), (3, '3 - Fair'), (4, '4 - Needs Improvement'), (5, '5 - Unsatisfactory')], default=2)),
                ('teacher_comment', models.TextField(blank=True)),
                ('promotion_status', models.CharField(choices=[('promoted', 'Promoted'), ('probation', 'Promoted on Probation'), ('not', 'Not Promoted'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='people.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
            options={
                'unique_together': {('student', 'session', 'term')},
            },
        ),
    ]
