# Generated by Django 6.0.5 on 2026-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studenttermreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('junior', 'Junior Secondary'), ('secondary', 'Senior Secondary')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='grade_level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclass',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
