# Generated by Django 6.0.5 on 2026-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentclass_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermreport',
            name='head_teacher_comment',
            field=models.TextField(blank=True),
        ),
    ]
